In [1]:
import sys

import matplotlib.pyplot as plt

import numpy as np
import torch

sys.path.insert(0, "../")

%load_ext autoreload
%autoreload 2

/cvlabdata2/home/davydov/miniconda3/envs/hmr_ssl/lib/python3.10/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [3]:
import src
from src.functional.renderer import ColoredRenderer

renderer = ColoredRenderer(img_size=(100, 100))
vertices = torch.randn((10, 4, 3))
print(vertices[0], "\n")

transformed_points = renderer.cameras.transform_points(vertices)
untransformed_points = renderer.cameras.unproject_points(
    transformed_points, world_coordinates=True, scaled_depth_input=True, from_ndc=True
)

print(transformed_points[0], "\n")
print(untransformed_points[0], "\n")

print((vertices - untransformed_points).abs().sum())

tensor([[ 1.7448, -0.5693,  0.2205],
        [-1.8953,  1.2106, -0.6533],
        [-1.1840, -1.3499, -0.0798],
        [ 0.2932,  1.4101, -1.5955]]) 

tensor([[ 1.7448, -0.5693, -0.0079],
        [-1.8953,  1.2106, -0.0167],
        [-1.1840, -1.3499, -0.0109],
        [ 0.2932,  1.4101, -0.0262]]) 

tensor([[ 1.7448, -0.5693,  0.2205],
        [-1.8953,  1.2106, -0.6533],
        [-1.1840, -1.3499, -0.0798],
        [ 0.2932,  1.4101, -1.5955]]) 

tensor(1.5423e-06)
